---
name: "Integration tests"

on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  secret-presence:
    runs-on: ubuntu-latest
    outputs:
      HAS_OTC_CRED: ${{ steps.secret-presence.outputs.HAS_OTC_CRED }}
      HAS_PG_CONNECTION_STRING: ${{ steps.secret-presence.outputs.HAS_PG_CONNECTION_STRING }}
    steps:
      - name: Check whether secrets exist
        id: secret-presence
        run: |
          [ ! -z "${{ secrets.obs_access_key_id }}" ] && 
          [ ! -z "${{ secrets.obs_secret_key }}" ] && echo "HAS_OTC_CRED=true" >> $GITHUB_OUTPUT
          [ ! -z "${{ secrets.pg_connection_string }}" ] && echo "HAS_PG_CONNECTION_STRING=true" >> $GITHUB_OUTPUT
          exit 0

  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: End-To-End Tests
        run: |
          ./gradlew compileJava compileTestJava
          ./gradlew test -DincludeTags="EndToEndTest" -PverboseTest=true
  obs-otc-test:
    runs-on: ubuntu-latest
    needs: [ secret-presence ]
    if: |
      needs.secret-presence.outputs.HAS_OTC_CRED
    env:
      OBS_ACCESS_KEY_ID: ${{ secrets.obs_access_key_id }}
      OBS_SECRET_ACCESS_KEY: ${{ secrets.obs_secret_key }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: OTC Cloud Tests
        run: |
          ./gradlew compileJava compileTestJava
          ./gradlew test -DincludeTags="OtcTest" -PverboseTest=true

  gaussdb-test:
    runs-on: ubuntu-latest
    needs: [ secret-presence ]
    if: |
      needs.secret-presence.outputs.HAS_PG_CONNECTION_STRING
    env:
      PG_CONNECTION_STRING: ${{ secrets.pg_connection_string }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: GaussDB Integration Tests
        run: |
          ./gradlew compileJava compileTestJava
          ./gradlew test -DincludeTags="GaussDbTest" -PverboseTest=true --no-parallel