---
name: "Integration tests"

on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: End-To-End Tests
        run: |
          ./gradlew compileJava compileTestJava
          ./gradlew test -DincludeTags="EndToEndTest" -PverboseTest=true
  cloud-test:
    runs-on: ubuntu-latest
    env:
      OBS_ACCESS_KEY_ID: ${{ secrets.obs_access_key_id }}
      OBS_SECRET_ACCESS_KEY: ${{ secrets.obs_secret_key }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java
      - name: OTC Cloud Tests
        run: ./gradlew test -DincludeTags="OtcTest" -PverboseTest=true